mem_notes/urls.py
from django.contrib import admin
from django.urls import path

from mem_notes.views import add_note, note_detail, note_list, policy

urlpatterns = [
    path('add_note/', add_note, name='add_note'),
    path('policy/', policy, name='policy'),
    path('', note_list, name='note_list'),
    path('note_detail/<int:pk>/', note_detail, name='note_detail'),
]

memories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mem_notes.urls')),
    path('accounts/', include('allauth.urls')),
]

mem_notes/models.py
from django.contrib.auth.models import User
from django.db import models
from location_field.models.plain import PlainLocationField


class Memories(models.Model):
    """
    Модель содержит поля для описывания воспоминаний
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=['city', 'location'], zoom=3)

    class Meta:
        verbose_name = 'Воспоминание'
        verbose_name_plural = 'Воспоминания'

    def __str__(self):
        return self.subject

mem_notes/forms.py
from django import forms
from location_field.forms.plain import PlainLocationField

from mem_notes.models import Memories


class RememberForm(forms.ModelForm):
    class Meta:
        model = Memories
        fields = ['subject', 'description', 'city', 'location']
        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': 'Тема',
                                              'class': 'm-1 form-control'}),
            'description': forms.Textarea(attrs={'placeholder': 'Как можно подробнее..',
                                                 'class': 'm-1 form-control' }),
            'city': forms.TextInput(attrs={'placeholder': 'Город, улицу и номер дома',
                                           'class': 'm-1 form-control'}),
            'location': forms.HiddenInput(attrs={'placeholder': 'Тут ничего не нужно',
                                                 'class': 'm-1 form-control'}),
        }

mem_notes/views.py
from allauth.socialaccount.models import SocialAccount
from django.http import Http404
from django.shortcuts import render, redirect

from mem_notes.forms import RememberForm
from mem_notes.models import Memories


def add_note(request):
    if request.method == "POST":
        form = RememberForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect(note_list)
    else:
        form = RememberForm()
    return render(request,
                  'mem_notes/add_note.html', {
                      'form': form,
                  })


def note_detail(request, pk):
    try:
        note = Memories.objects.get(pk=pk)
    except Memories.DoesNotExist:
        raise Http404('Такого нет тут!')

    return render(request, 'mem_notes/note_detail.html', context={'note': note})


def note_list(request):
    notes = Memories.objects.filter(owner=request.user.id)
    ex_data = ''
    try:
        ex_data = SocialAccount.objects.get(user=request.user.id).extra_data
    except SocialAccount.DoesNotExist:
        pass
    return render(request, 'mem_notes/note_list.html', context={
        'ex_data': ex_data,
        'notes': notes
    })


def policy(request):

    return render(request, 'mem_notes/policy.html', context={})

mem_notes/templates/mem_notes/add_note.html
{% extends 'mem_notes/base.html' %}
{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-8">
                <h1>Создать воспоминание.</h1>
                <form method="POST" class=" form-floating form-horizontal mt-3">{% csrf_token %}
                    <div class="form-group">
                        <div class="container">
                            <div class="row">
                                <div class="col-4">
                                    <label for="id_subject" class=" control-label">Событие:</label>
                                </div>
                                <div class="col-8">
                                    {{ form.subject }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div class="row">
                                <div class="col-4">
                                    <label for="id_description" class=" control-label">Подробности:</label>
                                </div>
                                <div class="col-8">
                                    {{ form.description }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div class="row">
                                <div class="col-4">
                                    <label for="id_city" class=" control-label">Место:</label>
                                </div>
                                <div class="col-8">
                                    {{ form.city }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="container">
                                <div class="row">
                                    <div class="col-4">
                                        <label for="id_location" class=" control-label">Координаты:</label>
                                    </div>
                                    <div class="col-8">
                                        {{ form.location }}
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="save btn btn-primary">Сохранить</button>
                </form>
            </div>
            <div class="col-2">

            </div>
        </div>
    </div>

{% endblock %}

mem_notes/templates/mem_notes/base.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
            crossorigin="anonymous"></script>
    {{ form.media }}
    {% load socialaccount %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-2">

        </div>
        <div class="col-sm-8">
            <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
                <div class="container-fluid">
                    {% if user.is_authenticated %}
                        <a class="nav-link active" aria-current="page" href="{% url 'add_note' %}">Добавить место</a>
                        <a class="nav-link" href="{% url 'note_list' %}">Список мест</a>


                        <img src="{{ ex_data.picture.data.url }}" alt="">
                        <p class="nav-link"> {{ user.first_name }} {{ user.last_name }} </p>
                        <a class="nav-link" href="{% url 'account_logout' %}">Выйти</a>

                    {% else %}
                    {% endif %}
                </div>
            </nav>
            <nav class=" navbar navbar-light bg-light mb-4">
                <div class="container-fluid">

                </div>
            </nav>
        </div>
        <div class="col-sm-2">

        </div>
    </div>
</div>



{% if user.is_authenticated %}
    {% block content %}
    {% endblock content %}
{% else %}
    <p class="text-center"> Этот сервис позволяет создовать заметки ихранить заметки с привязкой к координатам Google
        maps. Авторизовываться с помощью фейсбук.</p>
    <p class="text-center"> Для того что бы добовлять и просматривать места авторизуйтесь с помощью <a
            href="{% provider_login_url "facebook" method="oauth2" %}">Facebook OAuth2</a></p>


{% endif %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

mem_notes/templates/mem_notes/note_detail.html
{% extends 'mem_notes/base.html' %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
                <h2>{{ note.subject }}</h2>
                <p>{{ note.description }}</p>
                <p>Локация: <a href="https://www.google.com/maps?q={{ note.location }}&hl=ru&gl=ru">{{ note.city }}</a>
                </p>
                <p>Автор: <b>{{ note.owner }}</b></p>
            </div>
            <div class="col-md-3">
            </div>
        </div>
    </div>
{% endblock %}

mem_notes/templates/mem_notes/note_list.html
{% extends 'mem_notes/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-8">
                {% if not notes %}
                    <p>У вас нет не одной записи. Создайте их!</p>
                {% endif %}
                {% for note in notes %}
                    <div class="card mb-2">
                        <div class="card-header">
                            {{ note.subject }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ note.description }}</p>
                            <hr>
                            <p>{{ note.city }}</p>
                            <p>Автор: {{ note.owner }}</p>
                            <p><a href="{% url 'note_detail' note.pk %}" class="btn btn-secondary">Подробнее</a></p>
                        </div>

                    </div>
                {% endfor %}
            </div>
            <div class="col-sm-2">
            </div>
        </div>
    </div>
{% endblock %}

mem_notes/templates/mem_notes/policy.html
<h2><strong>Образец Политики конциденциальности 2021 без обработки персональных данных </strong></h2>
<h2><strong>Обратите внимание на порядок использования образца Политики конфиденциальности перед размещением на своем сайте!</strong></h2>
<p><strong>Образец Политики конфиденциальности</strong> может быть свободно использован полностью или в любой его части, в том числе переработан <strong>при условии размещения непосредственно под его текстом подписи с указанием источника заимствования и активной гипертекстовой ссылки на сайт www.it-lex.ru следующего вида</strong>: <em>Шаблон Политики конфиденциальности разработала &lt;a href="http://it-lex.ru" target="_blank" title="Составить политику конфиденциальности для сайта"&gt; <a href="/">Юридическая компания АйТи-Лекс</a></em>&lt;/a&gt;</p>
<p><em><div class="info">Образец Политики конфиденциальности разработан для лендингов и сайтов</em> с простой формой обратной связи. Политика также может подойти сайтам с формой подписки на новостные рассылки. Для <em>интернет-магазина</em> или <em>доски объявлений</em> с сложными формами регистрации рекомендуем использовать полную версию <em>Политики конфиденциальности</em>, которая регулирует вопросы обработки пользовательских персональных данных.</div></p>
<h1>Политика конфиденциальности</h1>
<p>Настоящий документ &laquo;Политика конфиденциальности&raquo; (далее по тексту &ndash; &laquo;Политика&raquo;) представляет собой правила использования /указать владельца сайта/ (далее &ndash; &laquo;мы&raquo; и/или &laquo;Администрация&raquo;) данных интернет-пользователей (далее &laquo;вы&raquo; и/или &laquo;Пользователь&raquo;), собираемых с использованием сайта / указать URL сайта/ (далее &ndash; &laquo;Сайт&raquo;).</p>
<h2>1. Обрабатываемые данные</h2>
<p>1.1. Мы не осуществляем сбор ваших <a href="/usloviya_ispolzovaniya_servisa/obrazec-politiki-konfidencialnosti-2017">персональных данных</a> с использованием Сайта.</p>
<p>1.2. Все данные, собираемые на Сайте, предоставляются и принимаются в обезличенной форме (далее &ndash; &laquo;Обезличенные данные&raquo;).</p>
<p>1.3. Обезличенные данные включают следующие сведения, которые не позволяют вас идентифицировать:</p>
<p>1.3.1. Информацию, которую вы предоставляете о себе самостоятельно с использованием онлайн-форм и программных модулей Сайта, включая имя и номер телефона и/или адрес электронной почты.</p>
<p>1.3.2. Данные, которые передаются в обезличенном виде в автоматическом режиме в зависимости от настроек используемого вами программного обеспечения.</p>
<p>1.4. Администрация вправе устанавливать требования к составу Обезличенных данных Пользователя, которые собираются использованием Сайта.</p>
<p>1.5. Если определенная информация не помечена как обязательная, ее предоставление или раскрытие осуществляется Пользователем на свое усмотрение. Одновременно вы даете информированное согласие на доступ неограниченного круга лиц к таким данным. Указанные данные становится общедоступными с момента предоставления и/или раскрытия в иной форме.</p>
<p>1.6. Администрация не осуществляет проверку достоверности предоставляемых данных и наличия у Пользователя необходимого согласия на их обработку в соответствии с настоящей Политикой, полагая, что Пользователь действует добросовестно, осмотрительно и прилагает все необходимые усилия к поддержанию такой информации в актуальном состоянии и получению всех необходимых согласий на ее использование.</p>
<p>1.7. Вы осознаете и принимаете возможность использования на Сайте программного обеспечения третьих лиц, в результате чего такие лица могут получать и передавать указанные в п.1.3 данные в обезличенном виде.</p>
<p><div class="info"> <strong>Пример!</strong> К указанному программному обеспечению третьих лиц относятся системы сбора статистики посещений Google Analytics и Яндекс.Метрика.</div></p>
<p>1.8. Состав и условия сбора обезличенных данных с использованием программного обеспечения третьих лиц определяются непосредственно их правообладателями и могут включать:</p>
<ul>
<li>данные браузера (тип, версия, cookie);</li>
<li>данные устройства и место его положения;</li>
<li>данные операционной системы (тип, версия, разрешение экрана);</li>
<li>данные запроса (время, источник перехода, IP-адрес).</li>
</ul>
<p>1.9. Администрация не несет ответственность за порядок использования Обезличенных данных Пользователя третьими лицами.</p>

<h2>2. Цели обработки данных</h2>
<p>2.1. Администрация использует данные в следующих целях:</p>
<p>2.1.1. Обработка поступающих запросов и связи с Пользователем;</p>
<p>2.1.2. Информационное обслуживание, включая рассылку рекламно-информационных материалов;</p>
<p>2.1.3. Проведение маркетинговых, статистических и иных исследований;</p>
<p>2.1.4. Таргетирование рекламных материалов на Сайте.</p>
<h2>3. Требования к защите данных</h2>
<p>3.1. Администрация осуществляет хранение данных и обеспечивает их охрану от несанкционированного доступа и распространения в соответствии с внутренними правилами и регламентами.</p>
<p>3.2. В отношении полученных данных сохраняется <a href="/usloviya_ispolzovaniya_servisa/obrazec-politiki-konfidencialnosti-2017">конфиденциальность</a>, за исключением случаев, когда они сделаны Пользователем общедоступными, а также когда используемые на Сайте технологии и программное обеспечение третьих лиц либо настройки используемого Пользователем программного обеспечения предусматривают открытый обмен с данными лицами и/или иными участниками и пользователями сети Интернет.</p>
<p>3.3. В целях повышения качества работы Администрация вправе хранить лог-файлы о действиях, совершенных Пользователем в рамках использования Сайта в течение 1 (Одного) года.</p>
<h2>4. Передача данных</h2>
<p>4.1. Администрация вправе передать данные третьим лицам в следующих случаях:</p>
<ul>
<li>Пользователь выразил свое согласие на такие действия, включая случаи применения Пользователем настроек используемого программного обеспечения, не ограничивающих предоставление определенной информации;</li>
<li>Передача необходима в рамках использования Пользователем функциональных возможностей Сайта;</li>
<li>Передача требуется в соответствии с целями обработки данных;</li>
<li>В связи с передачей Сайта во владение, пользование или собственность такого третьего лица;</li>
<li>По запросу суда или иного уполномоченного государственного органа в рамках установленной законодательством процедуры;</li>
<li>Для защиты прав и законных интересов Администрации в связи с допущенными Пользователем нарушениями.</li>
</ul>
<h2>5. Изменение Политики конфиденциальности</h2>
<p>5.1. Настоящая Политика может быть изменена или прекращена Администрацией в одностороннем порядке без предварительного уведомления Пользователя. Новая редакция Политики вступает в силу с момента ее размещения на Сайте, если иное не предусмотрено новой редакцией Политики.</p>
<p>5.2. Действующая редакция Политики находится на Сайте в сети Интернет по адресу. <br />Действующая редакция Политики от __________ 20__ г.</p>
<p>Политику разработала <a href="/">Юридическая компания АйТи-Лекс</a></p>
<p><div class="info"><strong>Обратите внимание!</strong> Образец Политики конфиденциальности не подходит для сайтов с формой регистрации и/или обратной связи, предусматривающими предоставление помимо номера телефона и/или электронного адреса иной персональной информации о пользователе. Поэтому не рекомендуем данный шаблон политики конфиденциальности для интернет-магазина, доски объявлений, торговой площадки и иных сайтов, обрабатывающих персональные данные пользователей. <br /> В случае обработки персональных данных, Политика конфиденциальности должна быть дополнена обязательными условиями о составе, основаниях, способах и целях обработки персональных данных, и получении согласия субъекта персональных данных с установленными в Политике правилами.</div></p>